#! /bin/bash

numlockx
setxkbmap -layout de,ru -option grp:shifts_toggle
setxkbmap -option ctrl:nocaps
xsetroot -cursor_name left_ptr
sxhkd &
#pactl load-module module-loopback latency_msec=1
picom &
redshift-gtk -l 48.386688914136336:8.628082127291922 &
nitrogen --restore &
polybar &
dunst &
dhcpcd-gtk &
flameshot &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config pointer_modifier      mod4

bspc config normal_border_color "#222222"
bspc config focused_border_color "#cccccc"
bspc config presel_feedback_color "#cccccc"

bspc rule -a Atril desktop='^1'
bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a Emacs desktop='^3'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a discord desktop='^6'
bspc rule -a steam desktop='^7'
bspc rule -a krateroid state=fullscreen
bspc rule -a Pavucontrol state=floating
